services:
  - type: web
    runtime: static
    name: yeetlb-web-v5
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_DEFAULT_BG_IMAGE
        value: /yeet-bg.jpg
      - key: VITE_PROXY_BASE
        sync: false
    routes:
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: yeetlb-proxy-v5
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: "10000"
      - key: CORS_ALLOW_ORIGIN
        sync: false
